**************************
*!* VFP GDI+ Constants
*!* 07/16/2005 - Created and modified for VFP
*!* by Craig Boyd from Dana Seaman's gdi+ typelib
*!* Dana's email addresses have been removed to 
*!* prevent spamming, they're easy enough to get
*!* as the tlb is freely available from CyberActiveX
*!* website.  Permission to post was granted 07-17-2005
**************************
*!* #DEFINE GDIplus_TYPELIB_DATE "Friday, 07 February 2003 02:40:20 UTC" 
*!* #DEFINE GDIplus_TYPELIB_AUTHOR "Dana Seaman"
*!* #DEFINE GDIplus_TYPELIB_VERSION "1.05" 
*!* #DEFINE GDIplus_TYPELIB_COPYRIGHT "Copyright 2003, Dana Seaman" 
*!* #DEFINE GDIplus_TYPELIB_DESCRIPTION "Windows GDI+ Type Library" 
*!* #DEFINE GDIplus_TYPELIB_URL "http://www.cyberactivex.com/" 

#DEFINE IPictureGUID "{7BF80980-BF32-101A-8BBB-00AA00300CAB}" 

#DEFINE ImageFormatUndefined  "{B96B3CA9-0728-11D3-9D7B-0000F81EF32E}" 
#DEFINE ImageFormatMemoryBMP  "{B96B3CAA-0728-11D3-9D7B-0000F81EF32E}" 
#DEFINE ImageFormatBMP    "{B96B3CAB-0728-11D3-9D7B-0000F81EF32E}" 
#DEFINE ImageFormatEMF    "{B96B3CAC-0728-11D3-9D7B-0000F81EF32E}" 
#DEFINE ImageFormatWMF    "{B96B3CAD-0728-11D3-9D7B-0000F81EF32E}" 
#DEFINE ImageFormatJPEG    "{B96B3CAE-0728-11D3-9D7B-0000F81EF32E}" 
#DEFINE ImageFormatPNG    "{B96B3CAF-0728-11D3-9D7B-0000F81EF32E}" 
#DEFINE ImageFormatGIF    "{B96B3CB0-0728-11D3-9D7B-0000F81EF32E}" 
#DEFINE ImageFormatTIFF    "{B96B3CB1-0728-11D3-9D7B-0000F81EF32E}" 
#DEFINE ImageFormatEXIF    "{B96B3CB2-0728-11D3-9D7B-0000F81EF32E}" 
#DEFINE ImageFormatIcon    "{B96B3CB5-0728-11D3-9D7B-0000F81EF32E}" 

#DEFINE FrameDimensionTime   "{6AEDBD6D-3FB5-418A-83A6-7F45229DC872}" 
#DEFINE FrameDimensionResolution "{84236F7B-3BD3-428F-8DAB-4EA1439CA315}" 
#DEFINE FrameDimensionPage   "{7462DC86-6180-4C7E-8E3F-EE7333A7A483}" 

#DEFINE FormatIDImageInformation "{E5836CBE-5EEF-0F1D-ACDE-AE4C43B608CE}" 
#DEFINE FormatIDJpegAppHeaders  "{1C4AFDCD-6177-43CF-ABC7-5F51AF39EE85}" 

#DEFINE EncoderCompression  "{E09D739D-CCD4-44EE-8EBA-3FBF8BE4FC58}" 
#DEFINE EncoderColorDepth  "{66087055-AD66-4C7C-9A18-38A2310B8337}" 
#DEFINE EncoderScanMethod  "{3A4E2661-3109-4E56-8536-42C156E7DCFA}" 
#DEFINE EncoderVersion   "{24D18C76-814A-41A4-BF53-1C219CCCF797}" 
#DEFINE EncoderRenderMethod  "{6D42C53A-229A-4825-8BB7-5C99E2B9A8B8}" 
#DEFINE EncoderQuality   "{1D5BE4B5-FA4A-452D-9CDD-5DB35105E7EB}" 
#DEFINE EncoderTransformation "{8D0EB2D1-A58E-4EA8-AA14-108074B7B6F9}" 
#DEFINE EncoderLuminanceTable "{EDB33BCE-0266-4A77-B904-27216099E717}" 
#DEFINE EncoderChrominanceTable "{F2E455DC-09B3-4316-8260-676ADA32481C}" 
#DEFINE EncoderSaveFlag   "{292266FC-AC40-47BF-8CFC-A85B89A655DE}" 

#DEFINE CodecIImageBytes  "{025D1823-6C7D-447B-BBDB-A3CBC3DFA2FC}" 

#define    PixelFormatIndexed      0x00010000 && Indexes into a palette
#define    PixelFormatGDI          0x00020000 && Is a GDI-supported format
#define    PixelFormatAlpha        0x00040000 && Has an alpha component
#define    PixelFormatPAlpha       0x00080000 && Pre-multiplied alpha
#define    PixelFormatExtended     0x00100000 && Extended color 16 bits/channel
#define    PixelFormatCanonical    0x00200000 

#define    PixelFormatUndefined       0
#define    PixelFormatDontCare        0

#define    PixelFormat1bppIndexed     (1 + (0x0100)+PixelFormatIndexed+PixelFormatGDI)
#define    PixelFormat4bppIndexed     (2 + (0x0400)+PixelFormatIndexed+PixelFormatGDI)
#define    PixelFormat8bppIndexed     (3 + (0x0800)+PixelFormatIndexed+PixelFormatGDI)
#define    PixelFormat16bppGrayScale  (4 + (0x1000)+PixelFormatExtended)
#define    PixelFormat16bppRGB555     (5 + (0x1000)+PixelFormatGDI)
#define    PixelFormat16bppRGB565     (6 + (0x1000)+PixelFormatGDI)
#define    PixelFormat16bppARGB1555   (7 + (0x1000)+PixelFormatAlpha+PixelFormatGDI)
#define    PixelFormat24bppRGB        (8 + (0x1800)+PixelFormatGDI)
#define    PixelFormat32bppRGB        (9 + (0x2000)+PixelFormatGDI)
#define    PixelFormat32bppARGB       (10+ (0x2000)+PixelFormatAlpha+PixelFormatGDI+PixelFormatCanonical)
#define    PixelFormat32bppPARGB      (11+ (0x2000)+PixelFormatAlpha+PixelFormatPAlpha+PixelFormatGDI)
#define    PixelFormat48bppRGB        (12+ (0x3000)+PixelFormatExtended)
#define    PixelFormat64bppARGB       (13+ (0x4000)+PixelFormatAlpha+PixelFormatCanonical+PixelFormatExtended)
#define    PixelFormat64bppPARGB      (14+ (0x4000)+PixelFormatAlpha+PixelFormatPAlpha+PixelFormatExtended)
#define    PixelFormatMax             15


#DEFINE AlphaShift 24 
#DEFINE RedShift 16 
#DEFINE GreenShift 8 
#DEFINE BlueShift 0 

#DEFINE AlphaMask -16777216 
#DEFINE RedMask  16711680 
#DEFINE GreenMask 65280 
#DEFINE BlueMask 255 

#DEFINE FillModeAlternate 0 
#DEFINE FillModeWinding  1 

#DEFINE QualityModeInvalid -1 
#DEFINE QualityModeDefault 0 
#DEFINE QualityModeLow  1 
#DEFINE QualityModeHigh  2 

#DEFINE CompositingModeSourceOver 0 
#DEFINE CompositingModeSourceCopy 1
 
#DEFINE CompositingQualityInvalid   -1 
#DEFINE CompositingQualityDefault   0 
#DEFINE CompositingQualityHighSpeed   1 
#DEFINE CompositingQualityHighQuality  2 
#DEFINE CompositingQualityGammaCorrected 3 
#DEFINE CompositingQualityAssumeLinear  4 

#DEFINE UnitWorld  0 
#DEFINE UnitDisplay  1 
#DEFINE UnitPixel  2 
#DEFINE UnitPoint  3 
#DEFINE UnitInch  4 
#DEFINE UnitDocument 5 
#DEFINE UnitMillimeter 6 

#DEFINE MetafileFrameUnitPixel   2 
#DEFINE MetafileFrameUnitPoint   3 
#DEFINE MetafileFrameUnitInch   4 
#DEFINE MetafileFrameUnitDocument  5 
#DEFINE MetafileFrameUnitMillimeter  6 
#DEFINE MetafileFrameUnitGdi   7 

#DEFINE CoordinateSpaceWorld 0 
#DEFINE CoordinateSpacePage  1 
#DEFINE CoordinateSpaceDevice 2 

#DEFINE WrapModeTile  0 
#DEFINE WrapModeTileFlipX 1 
#DEFINE WrapModeTileFlipy 2 
#DEFINE WrapModeTileFlipXY 3 
#DEFINE WrapModeClamp  4 

#DEFINE HatchStyleHorizontal    0 
#DEFINE HatchStyleVertical     1 
#DEFINE HatchStyleForwardDiagonal   2 
#DEFINE HatchStyleBackwardDiagonal   3 
#DEFINE HatchStyleCross      4 
#DEFINE HatchStyleDiagonalCross    5 
#DEFINE HatchStyle05Percent     6 
#DEFINE HatchStyle10Percent     7 
#DEFINE HatchStyle20Percent     8 
#DEFINE HatchStyle25Percent     9 
#DEFINE HatchStyle30Percent     10 
#DEFINE HatchStyle40Percent     11 
#DEFINE HatchStyle50Percent     12 
#DEFINE HatchStyle60Percent     13 
#DEFINE HatchStyle70Percent     14 
#DEFINE HatchStyle75Percent     15 
#DEFINE HatchStyle80Percent     16 
#DEFINE HatchStyle90Percent     17 
#DEFINE HatchStyleLightDownwardDiagonal  18 
#DEFINE HatchStyleLightUpwardDiagonal  19 
#DEFINE HatchStyleDarkDownwardDiagonal  20 
#DEFINE HatchStyleDarkUpwardDiagonal  21 
#DEFINE HatchStyleWideDownwardDiagonal  22 
#DEFINE HatchStyleWideUpwardDiagonal  23 
#DEFINE HatchStyleLightVertical    24 
#DEFINE HatchStyleLightHorizontal   25 
#DEFINE HatchStyleNarrowVertical   26 
#DEFINE HatchStyleNarrowHorizontal   27 
#DEFINE HatchStyleDarkVertical    28 
#DEFINE HatchStyleDarkHorizontal   29 
#DEFINE HatchStyleDashedDownwardDiagonal 30 
#DEFINE HatchStyleDashedUpwardDiagonal  31 
#DEFINE HatchStyleDashedHorizontal   32 
#DEFINE HatchStyleDashedVertical   33 
#DEFINE HatchStyleSmallConfetti    34 
#DEFINE HatchStyleLargeConfetti    35 
#DEFINE HatchStyleZigZag     36 
#DEFINE HatchStyleWave      37 
#DEFINE HatchStyleDiagonalBrick    38 
#DEFINE HatchStyleHorizontalBrick   39 
#DEFINE HatchStyleWeave      40 
#DEFINE HatchStylePlaid      41 
#DEFINE HatchStyleDivot      42 
#DEFINE HatchStyleDottedGrid    43 
#DEFINE HatchStyleDottedDiamond    44 
#DEFINE HatchStyleShingle     45 
#DEFINE HatchStyleTrellis     46 
#DEFINE HatchStyleSphere     47 
#DEFINE HatchStyleSmallGrid     48 
#DEFINE HatchStyleSmallCheckerBoard   49 
#DEFINE HatchStyleLargeCheckerBoard   50 
#DEFINE HatchStyleOutlinedDiamond   51 
#DEFINE HatchStyleSolidDiamond    52 
#DEFINE HatchStyleTotal      53
 
#DEFINE HatchStyleLargeGrid 4
#DEFINE HatchStyleMin  0 
#DEFINE HatchStyleMax  52

#DEFINE DashStyleSolid   0 
#DEFINE DashStyleDash   1 
#DEFINE DashStyleDot   2 
#DEFINE DashStyleDashDot  3 
#DEFINE DashStyleDashDotDot  4 
#DEFINE DashStyleCustom   5

#DEFINE DashCapFlat   0 
#DEFINE DashCapRound  2 
#DEFINE DashCapTriangle  3 

#DEFINE LineCapFlat    0 
#DEFINE LineCapSquare   1 
#DEFINE LineCapRound   2 
#DEFINE LineCapTriangle   3 
#DEFINE LineCapNoAnchor   16 
#DEFINE LineCapSquareAnchor  17 
#DEFINE LineCapRoundAnchor  18 
#DEFINE LineCapDiamondAnchor 19 
#DEFINE LineCapArrowAnchor  20 
#DEFINE LineCapAnchorMask  240 
#DEFINE LineCapCustom   255 

#DEFINE CustomLineCapTypeDefault   0 
#DEFINE CustomLineCapTypeAdjustableArrow 1 

#DEFINE LineJoinMiter   0 
#DEFINE LineJoinBevel   1 
#DEFINE LineJoinRound   2 
#DEFINE LineJoinMiterClipped 3 

#DEFINE PathPointTypeStart   0 
#DEFINE PathPointTypeLine   1 
#DEFINE PathPointTypeBezier   3 
#DEFINE PathPointTypeBezier3  3 
#DEFINE PathPointTypePathTypeMask 7 
#DEFINE PathPointTypeDashMode  16 
#DEFINE PathPointTypePathMarker  32 
#DEFINE PathPointTypeCloseSubpath 128 

#DEFINE WarpModePerspective 0 
#DEFINE WarpModeBilinear 1 

#DEFINE LinearGradientModeHorizontal  0 
#DEFINE LinearGradientModeVertical   1 
#DEFINE LinearGradientModeForwardDiagonal 2 
#DEFINE LinearGradientModeBackwardDiagonal 3 

#DEFINE CombineModeReplace  0 
#DEFINE CombineModeIntersect 1 
#DEFINE CombineModeUnion  2 
#DEFINE CombineModeXor   3 
#DEFINE CombineModeExclude  4 
#DEFINE CombineModeComplement 5 

#DEFINE ImageTypeUnknown 0 
#DEFINE ImageTypeBitmap  1 
#DEFINE ImageTypeMetafile 2 

#DEFINE InterpolationModeInvalid    -1 
#DEFINE InterpolationModeDefault    0 
#DEFINE InterpolationModeLowQuality    1 
#DEFINE InterpolationModeHighQuality   2 
#DEFINE InterpolationModeBilinear    3 
#DEFINE InterpolationModeBicubic    4 
#DEFINE InterpolationModeNearestNeighbor  5 
#DEFINE InterpolationModeHighQualityBilinear 6 
#DEFINE InterpolationModeHighQualityBicubic  7 

#DEFINE PenAlignmentCenter 0 
#DEFINE PenAlignmentInset 1 

#DEFINE BrushTypeSolidColor  0 
#DEFINE BrushTypeHatchFill  1 
#DEFINE BrushTypeTextureFill 2 
#DEFINE BrushTypePathGradient 3 
#DEFINE BrushTypeLinearGradient 4 

#DEFINE PenTypeSolidColor  0 
#DEFINE PenTypeHatchFill  1 
#DEFINE PenTypeTextureFill  2 
#DEFINE PenTypePathGradient  3 
#DEFINE PenTypeLinearGradient 4 
#DEFINE PenTypeUnknown   -1 

#DEFINE MatrixOrderPrepend 0 
#DEFINE MatrixOrderAppend 1 

#DEFINE GenericFontFamilySerif  0 
#DEFINE GenericFontFamilySansSerif 1 
#DEFINE GenericFontFamilyMonospace 2 

#DEFINE FontStyleRegular 0 
#DEFINE FontStyleBold  1 
#DEFINE FontStyleItalic  2 
#DEFINE FontStyleBoldItalic 3 
#DEFINE FontStyleUnderline 4 
#DEFINE FontStyleStrikeout 8 

#DEFINE SmoothingModeInvalid  -1 
#DEFINE SmoothingModeDefault  0 
#DEFINE SmoothingModeHighSpeed  1 
#DEFINE SmoothingModeHighQuality 2 
#DEFINE SmoothingModeNone   3 
#DEFINE SmoothingModeAntiAlias  4 

#DEFINE PixelOffsetModeInvalid  -1 
#DEFINE PixelOffsetModeDefault  0 
#DEFINE PixelOffsetModeHighSpeed 1 
#DEFINE PixelOffsetModeHighQuality 2 
#DEFINE PixelOffsetModeNone   3 
#DEFINE PixelOffsetModeHalf   4 

#DEFINE TextRenderingHintSystemDefault      0 
#DEFINE TextRenderingHintSingleBitPerPixelGridFit 1 
#DEFINE TextRenderingSingleBitPerPixel      2
#DEFINE TextRenderingHintAntiAliasGridFit   3 
#DEFINE TextRenderingAntiAlias              4
#DEFINE TextRenderingHintClearTypeGridFit   5 

#DEFINE MetafileTypeInvalid   0 
#DEFINE MetafileTypeWmf    1 
#DEFINE MetafileTypeWmfPlaceable 2 
#DEFINE MetafileTypeEmf    3 
#DEFINE MetafileTypeEmfPlusOnly  4 
#DEFINE MetafileTypeEmfPlusDual  5 

#DEFINE EmfTypeEmfOnly  3 
#DEFINE EmfTypeEmfPlusOnly 4 
#DEFINE EmfTypeEmfPlusDual 5 

#DEFINE ObjectTypeInvalid   0 
#DEFINE ObjectTypeBrush    1 
#DEFINE ObjectTypePen    2 
#DEFINE ObjectTypePath    3 
#DEFINE ObjectTypeRegion   4 
#DEFINE ObjectTypeImage    5 
#DEFINE ObjectTypeFont    6 
#DEFINE ObjectTypeStringFormat  7 
#DEFINE ObjectTypeImageAttributes 8 
#DEFINE ObjectTypeCustomLineCap  9 

#DEFINE ObjectTypeMax 9 
#DEFINE ObjectTypeMin 1 

#DEFINE StringFormatFlagsDirectionRightToLeft 1 
#DEFINE StringFormatFlagsDirectionVertical  2 
#DEFINE StringFormatFlagsNoFitBlackBox   4 
#DEFINE StringFormatFlagsDisplayFormatControl 32 
#DEFINE StringFormatFlagsNoFontFallback   1024 
#DEFINE StringFormatFlagsMeasureTrailingSpaces 2048 
#DEFINE StringFormatFlagsNoWrap     4096 
#DEFINE StringFormatFlagsLineLimit    8192 
#DEFINE StringFormatFlagsNoClip     16384 

#DEFINE StringTrimmingNone    0 
#DEFINE StringTrimmingCharacter   1 
#DEFINE StringTrimmingWord    2 
#DEFINE StringTrimmingEllipsisCharacter 3 
#DEFINE StringTrimmingEllipsisWord  4 
#DEFINE StringTrimmingEllipsisPath  5 

#DEFINE StringDigitSubstituteUser   0 
#DEFINE StringDigitSubstituteNone   1 
#DEFINE StringDigitSubstituteNational  2 
#DEFINE StringDigitSubstituteTraditional 3 

#DEFINE HotkeyPrefixNone 0 
#DEFINE HotkeyPrefixShow 1 
#DEFINE HotkeyPrefixHide 2 

#DEFINE StringAlignmentNear 0 
#DEFINE StringAlignmentCenter 1 
#DEFINE StringAlignmentFar  2 

#DEFINE DriverStringOptionsCmapLookup   1 
#DEFINE DriverStringOptionsVertical    2 
#DEFINE DriverStringOptionsRealizedAdvance  4 
#DEFINE DriverStringOptionsLimitSubpixel  8 

#DEFINE FlushIntentionFlush 0 
#DEFINE FlushIntentionSync 1 

#DEFINE EncoderParameterValueTypeByte   1 
#DEFINE EncoderParameterValueTypeASCII   2 
#DEFINE EncoderParameterValueTypeShort   3 
#DEFINE EncoderParameterValueTypeLong   4 
#DEFINE EncoderParameterValueTypeRational  5 
#DEFINE EncoderParameterValueTypeLongRange  6 
#DEFINE EncoderParameterValueTypeUndefined  7 
#DEFINE EncoderParameterValueTypeRationalRange 8 

#DEFINE EncoderValueColorTypeCMYK    0 
#DEFINE EncoderValueColorTypeYCCK    1 
#DEFINE EncoderValueCompressionLZW    2 
#DEFINE EncoderValueCompressionCCITT3   3 
#DEFINE EncoderValueCompressionCCITT4   4 
#DEFINE EncoderValueCompressionRle    5 
#DEFINE EncoderValueCompressionNone    6 
#DEFINE EncoderValueScanMethodInterlaced  7 
#DEFINE EncoderValueScanMethodNonInterlaced  8 
#DEFINE EncoderValueVersionGif87    9 
#DEFINE EncoderValueVersionGif89    10 
#DEFINE EncoderValueRenderProgressive   11 
#DEFINE EncoderValueRenderNonProgressive  12 
#DEFINE EncoderValueTransformRotate90   13 
#DEFINE EncoderValueTransformRotate180   14 
#DEFINE EncoderValueTransformRotate270   15 
#DEFINE EncoderValueTransformFlipHorizontal  16 
#DEFINE EncoderValueTransformFlipVertical  17 
#DEFINE EncoderValueMultiFrame     18 
#DEFINE EncoderValueLastFrame     19 
#DEFINE EncoderValueFlush      20 
#DEFINE EncoderValueFrameDimensionTime   21 
#DEFINE EncoderValueFrameDimensionResolution 22 
#DEFINE EncoderValueFrameDimensionPage   23 

#DEFINE EmfToWmfBitsFlagsDefault   0 
#DEFINE EmfToWmfBitsFlagsEmbedEmf   1 
#DEFINE EmfToWmfBitsFlagsIncludePlaceable 2 
#DEFINE EmfToWmfBitsFlagsNoXORClip   4 

#DEFINE WmfRecordTypeSetBkColor    66049 
#DEFINE WmfRecordTypeSetBkMode    65794 
#DEFINE WmfRecordTypeSetMapMode    5795 
#DEFINE WmfRecordTypeSetROP2    65796 
#DEFINE WmfRecordTypeSetRelAbs    65797 
#DEFINE WmfRecordTypeSetPolyFillMode  65798 
#DEFINE WmfRecordTypeSetStretchBltMode  65799 
#DEFINE WmfRecordTypeSetTextCharExtra  65800 
#DEFINE WmfRecordTypeSetTextColor   66057 
#DEFINE WmfRecordTypeSetTextJustification 66058 
#DEFINE WmfRecordTypeSetWindowOrg   66059 
#DEFINE WmfRecordTypeSetWindowExt   66060 
#DEFINE WmfRecordTypeSetViewportOrg   6061 
#DEFINE WmfRecordTypeSetViewportExt   66062 
#DEFINE WmfRecordTypeOffsetWindowOrg  66063 
#DEFINE WmfRecordTypeScaleWindowExt   6576 
#DEFINE WmfRecordTypeOffsetViewportOrg  6065 
#DEFINE WmfRecordTypeScaleViewportExt  66578 
#DEFINE WmfRecordTypeLineTo     66067 
#DEFINE WmfRecordTypeMoveTo     6068 
#DEFINE WmfRecordTypeExcludeClipRect  66581 
#DEFINE WmfRecordTypeIntersectClipRect  66582 
#DEFINE WmfRecordTypeArc     67607 
#DEFINE WmfRecordTypeEllipse    66584 
#DEFINE WmfRecordTypeFloodFill    66585 
#DEFINE WmfRecordTypePie     67610 
#DEFINE WmfRecordTypeRectangle    66587 
#DEFINE WmfRecordTypeRoundRect    67100 
#DEFINE WmfRecordTypePatBlt     67101 
#DEFINE WmfRecordTypeSaveDC     5566 
#DEFINE WmfRecordTypeSetPixel    66591 
#DEFINE WmfRecordTypeOffsetClipRgn   66080 
#DEFINE WmfRecordTypeTextOut    66849 
#DEFINE WmfRecordTypeBitBlt     67874 
#DEFINE WmfRecordTypeStretchBlt    68387 
#DEFINE WmfRecordTypePolygon    66340 
#DEFINE WmfRecordTypePolyline    66341 
#DEFINE WmfRecordTypeEscape     67110 
#DEFINE WmfRecordTypeRestoreDC    65831 
#DEFINE WmfRecordTypeFillRegion    66088 
#DEFINE WmfRecordTypeFrameRegion   66601 
#DEFINE WmfRecordTypeInvertRegion   65834 
#DEFINE WmfRecordTypePaintRegion   65835 
#DEFINE WmfRecordTypeSelectClipRegion  65836 
#DEFINE WmfRecordTypeSelectObject   65837 
#DEFINE WmfRecordTypeSetTextAlign   65838 
#DEFINE WmfRecordTypeDrawText    67119 
#DEFINE WmfRecordTypeChord     67632 
#DEFINE WmfRecordTypeSetMapperFlags   6097 
#DEFINE WmfRecordTypeExtTextOut    68146 
#DEFINE WmfRecordTypeSetDIBToDev   68915 
#DEFINE WmfRecordTypeSelectPalette   66100 
#DEFINE WmfRecordTypeRealizePalette   65589 
#DEFINE WmfRecordTypeAnimatePalette   66614 
#DEFINE WmfRecordTypeSetPalEntries   65591 
#DEFINE WmfRecordTypePolyPolygon   66872 
#DEFINE WmfRecordTypeResizePalette   65849 
#DEFINE WmfRecordTypeDIBBitBlt    67904 
#DEFINE WmfRecordTypeDIBStretchBlt   68417 
#DEFINE WmfRecordTypeDIBCreatePatternBrush 65858 
#DEFINE WmfRecordTypeStretchDIB    69443 
#DEFINE WmfRecordTypeExtFloodFill   66888 
#DEFINE WmfRecordTypeSetLayout    65865 
#DEFINE WmfRecordTypeResetDC    65868 
#DEFINE WmfRecordTypeStartDoc    65869 
#DEFINE WmfRecordTypeStartPage    65615 
#DEFINE WmfRecordTypeEndPage    65616 
#DEFINE WmfRecordTypeAbortDoc    65618 
#DEFINE WmfRecordTypeEndDoc     65630 
#DEFINE WmfRecordTypeDeleteObject   66032 
#DEFINE WmfRecordTypeCreatePalette   65783 
#DEFINE WmfRecordTypeCreateBrush   65784 
#DEFINE WmfRecordTypeCreatePatternBrush  66041 
#DEFINE WmfRecordTypeCreatePenIndirect  66298 
#DEFINE WmfRecordTypeCreateFontIndirect  66299 
#DEFINE WmfRecordTypeCreateBrushIndirect 66300 
#DEFINE WmfRecordTypeCreateBitmapIndirect 66301 
#DEFINE WmfRecordTypeCreateRegion   67327 

#DEFINE EmfRecordTypeHeader       1 
#DEFINE EmfRecordTypePolyBezier      2 
#DEFINE EmfRecordTypePolygon      3 
#DEFINE EmfRecordTypePolyline      4 
#DEFINE EmfRecordTypePolyBezierTo     5 
#DEFINE EmfRecordTypePolyLineTo      6 
#DEFINE EmfRecordTypePolyPolyline     7 
#DEFINE EmfRecordTypePolyPolygon     8 
#DEFINE EmfRecordTypeSetWindowExtEx     9 
#DEFINE EmfRecordTypeSetWindowOrgEx     10 
#DEFINE EmfRecordTypeSetViewportExtEx    11 
#DEFINE EmfRecordTypeSetViewportOrgEx    12 
#DEFINE EmfRecordTypeSetBrushOrgEx     13 
#DEFINE EmfRecordTypeEOF       14 
#DEFINE EmfRecordTypeSetPixelV      15 
#DEFINE EmfRecordTypeSetMapperFlags     16 
#DEFINE EmfRecordTypeSetMapMode      17 
#DEFINE EmfRecordTypeSetBkMode      18 
#DEFINE EmfRecordTypeSetPolyFillMode    19 
#DEFINE EmfRecordTypeSetROP2      20 
#DEFINE EmfRecordTypeSetStretchBltMode    21 
#DEFINE EmfRecordTypeSetTextAlign     22 
#DEFINE EmfRecordTypeSetColorAdjustment    23 
#DEFINE EmfRecordTypeSetTextColor     24 
#DEFINE EmfRecordTypeSetBkColor      25 
#DEFINE EmfRecordTypeOffsetClipRgn     26 
#DEFINE EmfRecordTypeMoveToEx      27 
#DEFINE EmfRecordTypeSetMetaRgn      28 
#DEFINE EmfRecordTypeExcludeClipRect    29 
#DEFINE EmfRecordTypeIntersectClipRect    30 
#DEFINE EmfRecordTypeScaleViewportExtEx    31 
#DEFINE EmfRecordTypeScaleWindowExtEx    32 
#DEFINE EmfRecordTypeSaveDC       33 
#DEFINE EmfRecordTypeRestoreDC      34 
#DEFINE EmfRecordTypeSetWorldTransform    35 
#DEFINE EmfRecordTypeModifyWorldTransform   36 
#DEFINE EmfRecordTypeSelectObject     37 
#DEFINE EmfRecordTypeCreatePen      38 
#DEFINE EmfRecordTypeCreateBrushIndirect   39 
#DEFINE EmfRecordTypeDeleteObject     40 
#DEFINE EmfRecordTypeAngleArc      41 
#DEFINE EmfRecordTypeEllipse      42 
#DEFINE EmfRecordTypeRectangle      43 
#DEFINE EmfRecordTypeRoundRect      44 
#DEFINE EmfRecordTypeArc       45 
#DEFINE EmfRecordTypeChord       46 
#DEFINE EmfRecordTypePie       47 
#DEFINE EmfRecordTypeSelectPalette     48 
#DEFINE EmfRecordTypeCreatePalette     49 
#DEFINE EmfRecordTypeSetPaletteEntries    50 
#DEFINE EmfRecordTypeResizePalette     51 
#DEFINE EmfRecordTypeRealizePalette     52 
#DEFINE EmfRecordTypeExtFloodFill     53 
#DEFINE EmfRecordTypeLineTo       54 
#DEFINE EmfRecordTypeArcTo       55 
#DEFINE EmfRecordTypePolyDraw      56 
#DEFINE EmfRecordTypeSetArcDirection    57 
#DEFINE EmfRecordTypeSetMiterLimit     58 
#DEFINE EmfRecordTypeBeginPath      59 
#DEFINE EmfRecordTypeEndPath      60 
#DEFINE EmfRecordTypeCloseFigure     61 
#DEFINE EmfRecordTypeFillPath      62 
#DEFINE EmfRecordTypeStrokeAndFillPath    63 
#DEFINE EmfRecordTypeStrokePath      64 
#DEFINE EmfRecordTypeFlattenPath     65 
#DEFINE EmfRecordTypeWidenPath      66 
#DEFINE EmfRecordTypeSelectClipPath     67 
#DEFINE EmfRecordTypeAbortPath      68 
#DEFINE EmfRecordTypeReserved_069     69 
#DEFINE EmfRecordTypeGdiComment      70 
#DEFINE EmfRecordTypeFillRgn      71 
#DEFINE EmfRecordTypeFrameRgn      72 
#DEFINE EmfRecordTypeInvertRgn      73 
#DEFINE EmfRecordTypePaintRgn      74 
#DEFINE EmfRecordTypeExtSelectClipRgn    75 
#DEFINE EmfRecordTypeBitBlt       76 
#DEFINE EmfRecordTypeStretchBlt      77 
#DEFINE EmfRecordTypeMaskBlt      78 
#DEFINE EmfRecordTypePlgBlt       79 
#DEFINE EmfRecordTypeSetDIBitsToDevice    80 
#DEFINE EmfRecordTypeStretchDIBits     81 
#DEFINE EmfRecordTypeExtCreateFontIndirect   82 
#DEFINE EmfRecordTypeExtTextOutA     83 
#DEFINE EmfRecordTypeExtTextOutW     84 
#DEFINE EmfRecordTypePolyBezier16     85 
#DEFINE EmfRecordTypePolygon16      86 
#DEFINE EmfRecordTypePolyline16      87 
#DEFINE EmfRecordTypePolyBezierTo16     88 
#DEFINE EmfRecordTypePolylineTo16     89 
#DEFINE EmfRecordTypePolyPolyline16     90 
#DEFINE EmfRecordTypePolyPolygon16     91 
#DEFINE EmfRecordTypePolyDraw16      92 
#DEFINE EmfRecordTypeCreateMonoBrush    93 
#DEFINE EmfRecordTypeCreateDIBPatternBrushPt  94 
#DEFINE EmfRecordTypeExtCreatePen     95 
#DEFINE EmfRecordTypePolyTextOutA     96 
#DEFINE EmfRecordTypePolyTextOutW     97 
#DEFINE EmfRecordTypeSetICMMode      98 
#DEFINE EmfRecordTypeCreateColorSpace    99 
#DEFINE EmfRecordTypeSetColorSpace     100 
#DEFINE EmfRecordTypeDeleteColorSpace    101 
#DEFINE EmfRecordTypeGLSRecord      102 
#DEFINE EmfRecordTypeGLSBoundedRecord    103 
#DEFINE EmfRecordTypePixelFormat     104 
#DEFINE EmfRecordTypeDrawEscape      105 
#DEFINE EmfRecordTypeExtEscape      106 
#DEFINE EmfRecordTypeStartDoc      107 
#DEFINE EmfRecordTypeSmallTextOut     108 
#DEFINE EmfRecordTypeForceUFIMapping    109 
#DEFINE EmfRecordTypeNamedEscape     110 
#DEFINE EmfRecordTypeColorCorrectPalette   111 
#DEFINE EmfRecordTypeSetICMProfileA     112 
#DEFINE EmfRecordTypeSetICMProfileW     113 
#DEFINE EmfRecordTypeAlphaBlend      114 
#DEFINE EmfRecordTypeSetLayout      115 
#DEFINE EmfRecordTypeTransparentBlt     116 
#DEFINE EmfRecordTypeReserved_117     117 
#DEFINE EmfRecordTypeGradientFill     118 
#DEFINE EmfRecordTypeSetLinkedUFIs     119 
#DEFINE EmfRecordTypeSetTextJustification   120 
#DEFINE EmfRecordTypeColorMatchToTargetW   121 
#DEFINE EmfRecordTypeCreateColorSpaceW    122 
#DEFINE EmfRecordTypeMax       122 
#DEFINE EmfRecordTypeMin       1 
#DEFINE EmfPlusRecordTypeInvalid     16384 
#DEFINE EmfPlusRecordTypeHeader      16385 
#DEFINE EmfPlusRecordTypeEndOfFile     16386 
#DEFINE EmfPlusRecordTypeComment     16387 
#DEFINE EmfPlusRecordTypeGetDC      16388 
#DEFINE EmfPlusRecordTypeMultiFormatStart   16389 
#DEFINE EmfPlusRecordTypeMultiFormatSection   16390 
#DEFINE EmfPlusRecordTypeMultiFormatEnd    16391 
#DEFINE EmfPlusRecordTypeObject      16392 
#DEFINE EmfPlusRecordTypeClear      16393 
#DEFINE EmfPlusRecordTypeFillRects     16394 
#DEFINE EmfPlusRecordTypeDrawRects     16395 
#DEFINE EmfPlusRecordTypeFillPolygon    16396 
#DEFINE EmfPlusRecordTypeDrawLines     16397 
#DEFINE EmfPlusRecordTypeFillEllipse    16398 
#DEFINE EmfPlusRecordTypeDrawEllipse    16399 
#DEFINE EmfPlusRecordTypeFillPie     16400 
#DEFINE EmfPlusRecordTypeDrawPie     16401 
#DEFINE EmfPlusRecordTypeDrawArc     16402 
#DEFINE EmfPlusRecordTypeFillRegion     16403 
#DEFINE EmfPlusRecordTypeFillPath     16404 
#DEFINE EmfPlusRecordTypeDrawPath     16405 
#DEFINE EmfPlusRecordTypeFillClosedCurve   16406 
#DEFINE EmfPlusRecordTypeDrawClosedCurve   16407 
#DEFINE EmfPlusRecordTypeDrawCurve     16408 
#DEFINE EmfPlusRecordTypeDrawBeziers    16409 
#DEFINE EmfPlusRecordTypeDrawImage     16410 
#DEFINE EmfPlusRecordTypeDrawImagePoints   16411 
#DEFINE EmfPlusRecordTypeDrawString     16412 
#DEFINE EmfPlusRecordTypeSetRenderingOrigin   16413 
#DEFINE EmfPlusRecordTypeSetAntiAliasMode   16414 
#DEFINE EmfPlusRecordTypeSetTextRenderingHint  16415 
#DEFINE EmfPlusRecordTypeSetTextContrast   16416 
#DEFINE EmfPlusRecordTypeSetInterpolationMode  16417 
#DEFINE EmfPlusRecordTypeSetPixelOffsetMode   16418 
#DEFINE EmfPlusRecordTypeSetCompositingMode   16419 
#DEFINE EmfPlusRecordTypeSetCompositingQuality  16420 
#DEFINE EmfPlusRecordTypeSave      16421 
#DEFINE EmfPlusRecordTypeRestore     16422 
#DEFINE EmfPlusRecordTypeBeginContainer    16423 
#DEFINE EmfPlusRecordTypeBeginContainerNoParams  16424 
#DEFINE EmfPlusRecordTypeEndContainer    16425 
#DEFINE EmfPlusRecordTypeSetWorldTransform   16426 
#DEFINE EmfPlusRecordTypeResetWorldTransform  16427 
#DEFINE EmfPlusRecordTypeMultiplyWorldTransform  16428 
#DEFINE EmfPlusRecordTypeTranslateWorldTransform 16429 
#DEFINE EmfPlusRecordTypeScaleWorldTransform  16430 
#DEFINE EmfPlusRecordTypeRotateWorldTransform  16431 
#DEFINE EmfPlusRecordTypeSetPageTransform   16432 
#DEFINE EmfPlusRecordTypeResetClip     16433 
#DEFINE EmfPlusRecordTypeSetClipRect    16434 
#DEFINE EmfPlusRecordTypeSetClipPath    16435 
#DEFINE EmfPlusRecordTypeSetClipRegion    16436 
#DEFINE EmfPlusRecordTypeOffsetClip     16437 
#DEFINE EmfPlusRecordTypeDrawDriverString   16438 
#DEFINE EmfPlusRecordTotal       16439 
#DEFINE EmfPlusRecordTypeMax      16438 
#DEFINE EmfPlusRecordTypeMin      16385 

#DEFINE ImageCodecFlagsEncoder   1 
#DEFINE ImageCodecFlagsDecoder   2 
#DEFINE ImageCodecFlagsSupportBitmap 4 
#DEFINE ImageCodecFlagsSupportVector 8 
#DEFINE ImageCodecFlagsSeekableEncode 16 
#DEFINE ImageCodecFlagsBlockingDecode 32 
#DEFINE ImageCodecFlagsBuiltin   65536 
#DEFINE ImageCodecFlagsSystem   131072 
#DEFINE ImageCodecFlagsUser    262144

#DEFINE ImageLockModeRead   1 
#DEFINE ImageLockModeWrite   2 
#DEFINE ImageLockModeUserInputBuf 4
 
#DEFINE ImageFlagsNone    0 
#DEFINE ImageFlagsScalable   1 
#DEFINE ImageFlagsHasAlpha   2 
#DEFINE ImageFlagsHasTranslucent 4 
#DEFINE ImageFlagsPartiallyScalable 8 
#DEFINE ImageFlagsColorSpaceRGB  16 
#DEFINE ImageFlagsColorSpaceCMYK 32 
#DEFINE ImageFlagsColorSpaceGRAY 64 
#DEFINE ImageFlagsColorSpaceYCBCR 128 
#DEFINE ImageFlagsColorSpaceYCCK 256 
#DEFINE ImageFlagsHasRealDPI  4096 
#DEFINE ImageFlagsHasRealPixelSize 8192 
#DEFINE ImageFlagsReadOnly   65536 
#DEFINE ImageFlagsCaching   131072 

#DEFINE RotateNoneFlipNone 0 
#DEFINE Rotate90FlipNone 1 
#DEFINE Rotate180FlipNone 2 
#DEFINE Rotate270FlipNone 3 
#DEFINE RotateNoneFlipX  4 
#DEFINE Rotate90FlipX  5 
#DEFINE Rotate180FlipX  6 
#DEFINE Rotate270FlipX  7 

#DEFINE Rotate180FlipXY  0 
#DEFINE Rotate270FlipXY  1 
#DEFINE RotateNoneFlipXY 2 
#DEFINE Rotate90FlipXY  3 
#DEFINE Rotate180FlipY  4 
#DEFINE Rotate270FlipY  5 
#DEFINE RotateNoneFlipY  6 
#DEFINE Rotate90FlipY  7 

#DEFINE PropertyTagTypeByte       1 
#DEFINE PropertyTagTypeASCII      2 
#DEFINE PropertyTagTypeShort      3 
#DEFINE PropertyTagTypeLong       4 
#DEFINE PropertyTagTypeRational      5 
#DEFINE PropertyTagTypeUndefined     7 
#DEFINE PropertyTagTypeSLONG      9 
#DEFINE PropertyTagTypeSRational     10 
#DEFINE PropertyTagExifIFD       34665 
#DEFINE PropertyTagsIFD        34853 
#DEFINE PropertyTagNewSubfileType     254 
#DEFINE PropertyTagSubfileType      255 
#DEFINE PropertyTagImageWidth      256 
#DEFINE PropertyTagImageHeight      257 
#DEFINE PropertyTagBitsPerSample     258 
#DEFINE PropertyTagCompression      259 
#DEFINE PropertyTagPhotometricInterp    262 
#DEFINE PropertyTagThreshHolding     263 
#DEFINE PropertyTagCellWidth      264 
#DEFINE PropertyTagCellHeight      265 
#DEFINE PropertyTagFillOrder      266 
#DEFINE PropertyTagDocumentName      269 
#DEFINE PropertyTagImageDescription     270 
#DEFINE PropertyTagEquipMake      271 
#DEFINE PropertyTagEquipModel      272 
#DEFINE PropertyTagStripOffsets      273 
#DEFINE PropertyTagOrientation      274 
#DEFINE PropertyTagSamplesPerPixel     277 
#DEFINE PropertyTagRowsPerStrip      278 
#DEFINE PropertyTagStripBytesCount     279 
#DEFINE PropertyTagMinSampleValue     280 
#DEFINE PropertyTagMaxSampleValue     281 
#DEFINE PropertyTagXResolution      282 
#DEFINE PropertyTagYResolution      283 
#DEFINE PropertyTagPlanarConfig      284 
#DEFINE PropertyTagPageName       285 
#DEFINE PropertyTagXPosition      286 
#DEFINE PropertyTagYPosition      287 
#DEFINE PropertyTagFreeOffset      288 
#DEFINE PropertyTagFreeByteCounts     289 
#DEFINE PropertyTagGrayResponseUnit     290 
#DEFINE PropertyTagGrayResponseCurve    291 
#DEFINE PropertyTagT4Option       292 
#DEFINE PropertyTagT6Option       293 
#DEFINE PropertyTagResolutionUnit     296 
#DEFINE PropertyTagPageNumber      297 
#DEFINE PropertyTagTransferFuncition    301 
#DEFINE PropertyTagSoftwareUsed      305 
#DEFINE PropertyTagDateTime       306 
#DEFINE PropertyTagArtist       315 
#DEFINE PropertyTagHostComputer      316 
#DEFINE PropertyTagPredictor      317 
#DEFINE PropertyTagWhitePoint      318 
#DEFINE PropertyTagPrimaryChromaticities   319 
#DEFINE PropertyTagColorMap       320 
#DEFINE PropertyTagHalftoneHints     321 
#DEFINE PropertyTagTileWidth      322 
#DEFINE PropertyTagTileLength      323 
#DEFINE PropertyTagTileOffset      324 
#DEFINE PropertyTagTileByteCounts     325 
#DEFINE PropertyTagInkSet       332 
#DEFINE PropertyTagInkNames       333 
#DEFINE PropertyTagNumberOfInks      334 
#DEFINE PropertyTagDotRange       336 
#DEFINE PropertyTagTargetPrinter     337 
#DEFINE PropertyTagExtraSamples      338 
#DEFINE PropertyTagSampleFormat      339 
#DEFINE PropertyTagSMinSampleValue     340 
#DEFINE PropertyTagSMaxSampleValue     341 
#DEFINE PropertyTagTransferRange     342 
#DEFINE PropertyTagJPEroc       512 
#DEFINE PropertyTagJPEGInterFormat     513 
#DEFINE PropertyTagJPEGInterLength     514 
#DEFINE PropertyTagJPEGRestartInterval    515 
#DEFINE PropertyTagJPEGLosslessPredictors   517 
#DEFINE PropertyTagJPEointTransforms    518 
#DEFINE PropertyTagJPEGQTables      519 
#DEFINE PropertyTagJPEGDCTables      520 
#DEFINE PropertyTagJPEGACTables      521 
#DEFINE PropertyTagYCbCrCoefficients    529 
#DEFINE PropertyTagYCbCrSubsampling     530 
#DEFINE PropertyTagYCbCrPositioning     531 
#DEFINE PropertyTagREFBlackWhite     532 
#DEFINE PropertyTagICCProfile      34675 
#DEFINE PropertyTagGamma       769 
#DEFINE PropertyTagICCProfileDescriptor    770 
#DEFINE PropertyTagSRGBRenderingIntent    771 
#DEFINE PropertyTagImageTitle      800 
#DEFINE PropertyTagCopyright      33432 
#DEFINE PropertyTagResolutionXUnit     20481 
#DEFINE PropertyTagResolutionYUnit     20482 
#DEFINE PropertyTagResolutionXLengthUnit   20483 
#DEFINE PropertyTagResolutionYLengthUnit   20484 
#DEFINE PropertyTagPrintFlags      20485 
#DEFINE PropertyTagPrintFlagsVersion    20486 
#DEFINE PropertyTagPrintFlagsCrop     20487 
#DEFINE PropertyTagPrintFlagsBleedWidth    20488 
#DEFINE PropertyTagPrintFlagsBleedWidthScale  20489 
#DEFINE PropertyTagHalftoneLPI      20490 
#DEFINE PropertyTagHalftoneLPIUnit     20491 
#DEFINE PropertyTagHalftoneDegree     20492 
#DEFINE PropertyTagHalftoneShape     20493 
#DEFINE PropertyTagHalftoneMisc      20494 
#DEFINE PropertyTagHalftoneScreen     20495 
#DEFINE PropertyTagJPEGQuality      20496 
#DEFINE PropertyTagGridSize       20497 
#DEFINE PropertyTagThumbnailFormat     20498 
#DEFINE PropertyTagThumbnailWidth     20499 
#DEFINE PropertyTagThumbnailHeight     20500 
#DEFINE PropertyTagThumbnailColorDepth    20501 
#DEFINE PropertyTagThumbnailPlanes     20502 
#DEFINE PropertyTagThumbnailRawBytes    20503 
#DEFINE PropertyTagThumbnailSize     20504 
#DEFINE PropertyTagThumbnailCompressedSize   20505 
#DEFINE PropertyTagColorTransferFunction   20506 
#DEFINE PropertyTagThumbnailData     20507 
#DEFINE PropertyTagThumbnailImageWidth    20512 
#DEFINE PropertyTagThumbnailImageHeight    20513 
#DEFINE PropertyTagThumbnailBitsPerSample   20514 
#DEFINE PropertyTagThumbnailCompression    20515 
#DEFINE PropertyTagThumbnailPhotometricInterp  20516 
#DEFINE PropertyTagThumbnailImageDescription  20517 
#DEFINE PropertyTagThumbnailEquipMake    20518 
#DEFINE PropertyTagThumbnailEquipModel    20519 
#DEFINE PropertyTagThumbnailStripOffsets   20520 
#DEFINE PropertyTagThumbnailOrientation    20521 
#DEFINE PropertyTagThumbnailSamplesPerPixel   20522 
#DEFINE PropertyTagThumbnailRowsPerStrip   20523 
#DEFINE PropertyTagThumbnailStripBytesCount   20524 
#DEFINE PropertyTagThumbnailResolutionX    20525 
#DEFINE PropertyTagThumbnailResolutionY    20526 
#DEFINE PropertyTagThumbnailPlanarConfig   20527 
#DEFINE PropertyTagThumbnailResolutionUnit   20528 
#DEFINE PropertyTagThumbnailTransferFunction  20529 
#DEFINE PropertyTagThumbnailSoftwareUsed   20530 
#DEFINE PropertyTagThumbnailDateTime    20531 
#DEFINE PropertyTagThumbnailArtist     20532 
#DEFINE PropertyTagThumbnailWhitePoint    20533 
#DEFINE PropertyTagThumbnailPrimaryChromaticities 20534 
#DEFINE PropertyTagThumbnailYCbCrCoefficients  20535 
#DEFINE PropertyTagThumbnailYCbCrSubsampling  20536 
#DEFINE PropertyTagThumbnailYCbCrPositioning  20537 
#DEFINE PropertyTagThumbnailRefBlackWhite   20538 
#DEFINE PropertyTagThumbnailCopyRight    20539 
#DEFINE PropertyTagLuminanceTable     20624 
#DEFINE PropertyTagChrominanceTable     20625 
#DEFINE PropertyTagFrameDelay      20736 
#DEFINE PropertyTagLoopCount      20737 
#DEFINE PropertyTagPixelUnit      20752 
#DEFINE PropertyTagPixelPerUnitX     20753 
#DEFINE PropertyTagPixelPerUnitY     20754 
#DEFINE PropertyTagPaletteHistogram     20755 
#DEFINE PropertyTagExifExposureTime     33434 
#DEFINE PropertyTagExifFNumber      33437 
#DEFINE PropertyTagExifExposureProg     34850 
#DEFINE PropertyTagExifSpectralSense    34852 
#DEFINE PropertyTagExifISOSpeed      34855 
#DEFINE PropertyTagExifOECF       34856 
#DEFINE PropertyTagExifVer       36864 
#DEFINE PropertyTagExifDTOrig      36867 
#DEFINE PropertyTagExifDTDigitized     36868 
#DEFINE PropertyTagExifCompConfig     37121 
#DEFINE PropertyTagExifCompBPP      37122 
#DEFINE PropertyTagExifShutterSpeed     37377 
#DEFINE PropertyTagExifAperture      37378 
#DEFINE PropertyTagExifBrightness     37379 
#DEFINE PropertyTagExifExposureBias     37380 
#DEFINE PropertyTagExifMaxAperture     37381 
#DEFINE PropertyTagExifSubjectDist     37382 
#DEFINE PropertyTagExifMeteringMode     37383 
#DEFINE PropertyTagExifLightSource     37384 
#DEFINE PropertyTagExifFlash      37385 
#DEFINE PropertyTagExifFocalLength     37386 
#DEFINE PropertyTagExifMakerNote     37500 
#DEFINE PropertyTagExifUserComment     37510 
#DEFINE PropertyTagExifDTSubsec      37520 
#DEFINE PropertyTagExifDTOrigSS      37521 
#DEFINE PropertyTagExifDTDigSS      37522 
#DEFINE PropertyTagExifFPXVer      40960 
#DEFINE PropertyTagExifColorSpace     40961 
#DEFINE PropertyTagExifPixXDim      40962 
#DEFINE PropertyTagExifPixYDim      40963 
#DEFINE PropertyTagExifRelatedWav     40964 
#DEFINE PropertyTagExifInterop      40965 
#DEFINE PropertyTagExifFlashEnergy     41483 
#DEFINE PropertyTagExifSpatialFR     41484 
#DEFINE PropertyTagExifFocalXRes     41486 
#DEFINE PropertyTagExifFocalYRes     41487 
#DEFINE PropertyTagExifFocalResUnit     41488 
#DEFINE PropertyTagExifSubjectLoc     41492 
#DEFINE PropertyTagExifExposureIndex    41493 
#DEFINE PropertyTagExifSensingMethod    41495 
#DEFINE PropertyTagExifFileSource     41728 
#DEFINE PropertyTagExifSceneType     41729 
#DEFINE PropertyTagExifCfaPattern     41730
 
#DEFINE PropertyTagGpsVer    0 
#DEFINE PropertyTagGpsLatitudeRef  1 
#DEFINE PropertyTagGpsLongitudeRef  3 
#DEFINE PropertyTagGpsAltitudeRef  5 
#DEFINE PropertyTagGpsGpsTime   7 
#DEFINE PropertyTagGpsGpsSatellites  8 
#DEFINE PropertyTagGpsGpsStatus   9 
#DEFINE PropertyTagGpsGpsMeasureMode 10 
#DEFINE PropertyTagGpsGpsDop   11 
#DEFINE PropertyTagGpsSpeedRef   12 
#DEFINE PropertyTagGpsTrackRef   14 
#DEFINE PropertyTagGpsImgDirRef   16 
#DEFINE PropertyTagGpsMapDatum   18 
#DEFINE PropertyTagGpsDestLatRef  19 
#DEFINE PropertyTagGpsDestLongRef  21 
#DEFINE PropertyTagGpsDestBearRef  23 
#DEFINE PropertyTagGpsDestDistRef  25 

#DEFINE Ok      0 
#DEFINE GenericError   1 
#DEFINE InvalidParameter  2 
#DEFINE OutOfMemory    3 
#DEFINE ObjectBusy    4 
#DEFINE InsufficientBuffer  5 
#DEFINE NotImplemented   6 
#DEFINE Win32Error    7 
#DEFINE WrongState    8 
#DEFINE Aborted     9 
#DEFINE FileNotFound   10 
#DEFINE ValueOverflow   11 
#DEFINE AccessDenied   12 
#DEFINE UnknownImageFormat  13 
#DEFINE FontFamilyNotFound  14 
#DEFINE FontStyleNotFound  15 
#DEFINE NotTrueTypeFont   16 
#DEFINE UnsupportedlusVersion 17 
#DEFINE lusNotInitialized  18 
#DEFINE PropertyNotFound  19 
#DEFINE PropertyNotSupported 20 

#DEFINE StatusOk      0 
#DEFINE StatusGenericError   1 
#DEFINE StatusInvalidParameter  2 
#DEFINE StatusOutOfMemory    3 
#DEFINE StatusObjectBusy    4 
#DEFINE StatusInsufficientBuffer  5 
#DEFINE StatusNotImplemented   6 
#DEFINE StatusWin32Error    7 
#DEFINE StatusWrongState    8 
#DEFINE StatusAborted     9 
#DEFINE StatusFileNotFound   10 
#DEFINE StatusValueOverflow   11 
#DEFINE StatusAccessDenied   12 
#DEFINE StatusUnknownImageFormat  13 
#DEFINE StatusFontFamilyNotFound  14 
#DEFINE StatusFontStyleNotFound  15 
#DEFINE StatusNotTrueTypeFont   16 
#DEFINE StatusUnsupportedlusVersion 17 
#DEFINE StatusGdiPlusNotInitialized  18 
#DEFINE StatusPropertyNotFound  19 
#DEFINE StatusPropertyNotSupported 20 

#DEFINE ColorMatrixFlagsDefault  0 
#DEFINE ColorMatrixFlagsSkipGrays 1 
#DEFINE ColorMatrixFlagsAltGray  2 

#DEFINE ColorAdjustTypeDefault 0 
#DEFINE ColorAdjustTypeBitmap 1 
#DEFINE ColorAdjustTypeBrush 2 
#DEFINE ColorAdjustTypePen  3 
#DEFINE ColorAdjustTypeText  4 
#DEFINE ColorAdjustTypeCount 5 
#DEFINE ColorAdjustTypeAny  6 

#DEFINE ColorModeARGB32 0 
#DEFINE ColorModeARGB64 1 

#DEFINE ColorChannelFlagsC  0 
#DEFINE ColorChannelFlagsM  1 
#DEFINE ColorChannelFlagsY  2 
#DEFINE ColorChannelFlagsK  3 
#DEFINE ColorChannelFlagsLast 4 

#DEFINE PaletteFlagsHasAlpha 1 
#DEFINE PaletteFlagsGrayScale 2 
#DEFINE PaletteFlagsHalftone 4 

#DEFINE ARGB_AliceBlue     -984833 
#DEFINE ARGB_AntiqueWhite    -332841 
#DEFINE ARGB_Aqua      -16711681 
#DEFINE ARGB_Aquamarine    -8388652 
#DEFINE ARGB_Azure      -983041 
#DEFINE ARGB_Beige      -657956 
#DEFINE ARGB_Bisque      -6972 
#DEFINE ARGB_Black      -16777216 
#DEFINE ARGB_BlanchedAlmond    -5171 
#DEFINE ARGB_Blue     -16776961
#DEFINE ARGB_BlueViolet     -7722014 
#DEFINE ARGB_Brown      -5952982 
#DEFINE ARGB_BurlyWood     -2180985 
#DEFINE ARGB_CadetBlue     -10510688 
#DEFINE ARGB_Chartreuse     -8388864 
#DEFINE ARGB_Chocolate     -2987746 
#DEFINE ARGB_Coral      -32944 
#DEFINE ARGB_CornflowerBlue    -10185235 
#DEFINE ARGB_Cornsilk     -1828 
#DEFINE ARGB_Crimson      -2354116 
#DEFINE ARGB_Cyan      -16711681 
#DEFINE ARGB_DarkBlue     -16777077 
#DEFINE ARGB_DarkCyan     -16741493 
#DEFINE ARGB_DarkGoldenrod    -4684277 
#DEFINE ARGB_DarkGray     -5658199 
#DEFINE ARGB_DarkGreen     -16751616 
#DEFINE ARGB_DarkKhaki     -4343957 
#DEFINE ARGB_DarkMagenta     -7667573 
#DEFINE ARGB_DarkOliveGreen    -11179217 
#DEFINE ARGB_DarkOrange     -29696 
#DEFINE ARGB_DarkOrchid     -6737204 
#DEFINE ARGB_DarkRed      -7667712 
#DEFINE ARGB_DarkSalmon     -1468806 
#DEFINE ARGB_DarkSeaGreen    -7357301 
#DEFINE ARGB_DarkSlateBlue    -12042869 
#DEFINE ARGB_DarkSlateGray    -13676721 
#DEFINE ARGB_DarkTurquoise    -16724271 
#DEFINE ARGB_DarkViolet     -7077677 
#DEFINE ARGB_DeepPink     -60269 
#DEFINE ARGB_DeepSkyBlue     -16728065 
#DEFINE ARGB_DimGray      -9868951 
#DEFINE ARGB_DodgerBlue     -14774017 
#DEFINE ARGB_Firebrick     -5103070 
#DEFINE ARGB_FloralWhite     -1296 
#DEFINE ARGB_ForestGreen     -14513374 
#DEFINE ARGB_Fuchsia      -65281 
#DEFINE ARGB_Gainsboro     -2302756 
#DEFINE ARGB_GhostWhite     -460545 
#DEFINE ARGB_Gold      -10496 
#DEFINE ARGB_Goldenrod     -2448096 
#DEFINE ARGB_Gray      -8355712
#DEFINE ARGB_Green      -16711936
#DEFINE ARGB_GreenYellow     -5374161 
#DEFINE ARGB_Honeydew     -983056 
#DEFINE ARGB_HotPink      -38476 
#DEFINE ARGB_IndianRed     -3318692 
#DEFINE ARGB_Indigo      -11861886 
#DEFINE ARGB_Ivory      -16 
#DEFINE ARGB_Khaki      -989556 
#DEFINE ARGB_Lavender     -1644806 
#DEFINE ARGB_LavenderBlush    -3851 
#DEFINE ARGB_LawnGreen     -8586240 
#DEFINE ARGB_LemonChiffon    -1331 
#DEFINE ARGB_LightBlue     -5383962 
#DEFINE ARGB_LightCoral     -1015680 
#DEFINE ARGB_LightCyan     -2031617 
#DEFINE ARGB_LightGoldenrodYellow -329006 
#DEFINE ARGB_LightGray     -2894893 
#DEFINE ARGB_LightGreen     -7278960 
#DEFINE ARGB_LightPink     -18751 
#DEFINE ARGB_LightSalmon     -24454 
#DEFINE ARGB_LightSeaGreen    -14634326 
#DEFINE ARGB_LightSkyBlue    -7876870 
#DEFINE ARGB_LightSlateGray    -8943463 
#DEFINE ARGB_LightSteelBlue    -5192482 
#DEFINE ARGB_LightYellow     -32 
#DEFINE ARGB_Lime      -16711936 
#DEFINE ARGB_LimeGreen     -13447886 
#DEFINE ARGB_Linen      -331546 
#DEFINE ARGB_Magenta      -65281 
#DEFINE ARGB_Maroon      -8388608 
#DEFINE ARGB_MediumAquamarine  -10039894 
#DEFINE ARGB_MediumBlue    -16777011 
#DEFINE ARGB_MediumOrchid   -4565549 
#DEFINE ARGB_MediumPurple   -7114533 
#DEFINE ARGB_MediumSeaGreen   -12799119
#DEFINE ARGB_MediumSlateBlue   -8689426 
#DEFINE ARGB_MediumSpringGreen  -16713062 
#DEFINE ARGB_MediumTurquoise    -12004916 
#DEFINE ARGB_MediumVioletRed    -3730043 
#DEFINE ARGB_MidnightBlue    -15132304 
#DEFINE ARGB_MintCream     -655366 
#DEFINE ARGB_MistyRose     -6943 
#DEFINE ARGB_Moccasin     -6987 
#DEFINE ARGB_NavajoWhite     -8531 
#DEFINE ARGB_Navy      -16777088 
#DEFINE ARGB_OldLace      -133658 
#DEFINE ARGB_Olive      -8355840 
#DEFINE ARGB_OliveDrab     -9728477 
#DEFINE ARGB_Orange      -23296 
#DEFINE ARGB_OrangeRed     -47872 
#DEFINE ARGB_Orchid      -2461482 
#DEFINE ARGB_PaleGoldenrod    -1120086 
#DEFINE ARGB_PaleGreen     -6751336 
#DEFINE ARGB_PaleTurquoise    -5247250 
#DEFINE ARGB_PaleVioletRed    -2396013 
#DEFINE ARGB_PapayaWhip     -4139 
#DEFINE ARGB_PeachPuff     -9543 
#DEFINE ARGB_Peru      -3308225 
#DEFINE ARGB_Pink      -16181 
#DEFINE ARGB_Plum      -2252579 
#DEFINE ARGB_PowderBlue     -5185306 
#DEFINE ARGB_Purple      -8388480 
#DEFINE ARGB_Red     -65536
#DEFINE ARGB_RosyBrown     -4419697 
#DEFINE ARGB_RoyalBlue     -12490271 
#DEFINE ARGB_SaddleBrown     -7650029 
#DEFINE ARGB_Salmon      -360334 
#DEFINE ARGB_SandyBrown     -744352 
#DEFINE ARGB_SeaGreen     -13726889 
#DEFINE ARGB_SeaShell     -2578 
#DEFINE ARGB_Sienna      -6270419 
#DEFINE ARGB_Silver      -4144960 
#DEFINE ARGB_SkyBlue      -7876885 
#DEFINE ARGB_SlateBlue     -9807155 
#DEFINE ARGB_SlateGray     -9404272 
#DEFINE ARGB_Snow      -1286 
#DEFINE ARGB_SpringGreen     -16711809 
#DEFINE ARGB_SteelBlue     -12156236 
#DEFINE ARGB_Tan       -2968436 
#DEFINE ARGB_Teal      -16744320 
#DEFINE ARGB_Thistle      -2572328 
#DEFINE ARGB_Tomato      -40121 
#DEFINE ARGB_Transparent    16777215 
#DEFINE ARGB_Turquoise     -12525360 
#DEFINE ARGB_Violet      -1146130 
#DEFINE ARGB_Wheat      -663885 
#DEFINE ARGB_White      -1 
#DEFINE ARGB_WhiteSmoke     -657931 
#DEFINE ARGB_Yellow      -256 
#DEFINE ARGB_YellowGreen     -6632142 


#DEFINE KnownColorActiveBorder     1
#DEFINE KnownColorActiveCaption     2
#DEFINE KnownColorActiveCaptionText     3
#DEFINE KnownColorAppWorkspace     4
#DEFINE KnownColorControl     5
#DEFINE KnownColorControlDark     6
#DEFINE KnownColorControlDarkDark     7
#DEFINE KnownColorControlLight     8
#DEFINE KnownColorControlLightLight     9
#DEFINE KnownColorControlText     10
#DEFINE KnownColorDesktop     11
#DEFINE KnownColorGrayText     12
#DEFINE KnownColorHighlight     13
#DEFINE KnownColorHighlightText     14
#DEFINE KnownColorHotTrack     15
#DEFINE KnownColorInactiveBorder     16
#DEFINE KnownColorInactiveCaption     17
#DEFINE KnownColorInactiveCaptionText     18
#DEFINE KnownColorInfo     19
#DEFINE KnownColorInfoText     20
#DEFINE KnownColorMenu     21
#DEFINE KnownColorMenuText     22
#DEFINE KnownColorScrollBar     23
#DEFINE KnownColorWindow     24
#DEFINE KnownColorWindowFrame     25
#DEFINE KnownColorWindowText     26
#DEFINE KnownColorTransparent     27
#DEFINE KnownColorAliceBlue     28
#DEFINE KnownColorAntiqueWhite     29
#DEFINE KnownColorAqua     30
#DEFINE KnownColorAquamarine     31
#DEFINE KnownColorAzure     32
#DEFINE KnownColorBeige     33
#DEFINE KnownColorBisque     34
#DEFINE KnownColorBlack     35
#DEFINE KnownColorBlanchedAlmond     36
#DEFINE KnownColorBlue     37
#DEFINE KnownColorBlueViolet     38
#DEFINE KnownColorBrown     39
#DEFINE KnownColorBurlyWood     40
#DEFINE KnownColorCadetBlue     41
#DEFINE KnownColorChartreuse     42
#DEFINE KnownColorChocolate     43
#DEFINE KnownColorCoral     44
#DEFINE KnownColorCornflowerBlue     45
#DEFINE KnownColorCornsilk     46
#DEFINE KnownColorCrimson     47
#DEFINE KnownColorCyan     48
#DEFINE KnownColorDarkBlue     49
#DEFINE KnownColorDarkCyan     50
#DEFINE KnownColorDarkGoldenrod     51
#DEFINE KnownColorDarkGray     52
#DEFINE KnownColorDarkGreen     53
#DEFINE KnownColorDarkKhaki     54
#DEFINE KnownColorDarkMagenta     55
#DEFINE KnownColorDarkOliveGreen     56
#DEFINE KnownColorDarkOrange     57
#DEFINE KnownColorDarkOrchid     58
#DEFINE KnownColorDarkRed     59
#DEFINE KnownColorDarkSalmon     60
#DEFINE KnownColorDarkSeaGreen     61
#DEFINE KnownColorDarkSlateBlue     62
#DEFINE KnownColorDarkSlateGray     63
#DEFINE KnownColorDarkTurquoise     64
#DEFINE KnownColorDarkViolet     65
#DEFINE KnownColorDeepPink     66
#DEFINE KnownColorDeepSkyBlue     67
#DEFINE KnownColorDimGray     68
#DEFINE KnownColorDodgerBlue     69
#DEFINE KnownColorFirebrick     70
#DEFINE KnownColorFloralWhite     71
#DEFINE KnownColorForestGreen     72
#DEFINE KnownColorFuchsia     73
#DEFINE KnownColorGainsboro     74
#DEFINE KnownColorGhostWhite     75
#DEFINE KnownColorGold     76
#DEFINE KnownColorGoldenrod     77
#DEFINE KnownColorGray     78
#DEFINE KnownColorGreen     79
#DEFINE KnownColorGreenYellow     80
#DEFINE KnownColorHoneydew     81
#DEFINE KnownColorHotPink     82
#DEFINE KnownColorIndianRed     83
#DEFINE KnownColorIndigo     84
#DEFINE KnownColorIvory     85
#DEFINE KnownColorKhaki     86
#DEFINE KnownColorLavender     87
#DEFINE KnownColorLavenderBlush     88
#DEFINE KnownColorLawnGreen     89
#DEFINE KnownColorLemonChiffon     90
#DEFINE KnownColorLightBlue     91
#DEFINE KnownColorLightCoral     92
#DEFINE KnownColorLightCyan     93
#DEFINE KnownColorLightGoldenrodYellow     94
#DEFINE KnownColorLightGray     95
#DEFINE KnownColorLightGreen     96
#DEFINE KnownColorLightPink     97
#DEFINE KnownColorLightSalmon     98
#DEFINE KnownColorLightSeaGreen     99
#DEFINE KnownColorLightSkyBlue     100
#DEFINE KnownColorLightSlateGray     101
#DEFINE KnownColorLightSteelBlue     102
#DEFINE KnownColorLightYellow     103
#DEFINE KnownColorLime     104
#DEFINE KnownColorLimeGreen     105
#DEFINE KnownColorLinen     106
#DEFINE KnownColorMagenta     107
#DEFINE KnownColorMaroon     108
#DEFINE KnownColorMediumAquamarine     109
#DEFINE KnownColorMediumBlue     110
#DEFINE KnownColorMediumOrchid     111
#DEFINE KnownColorMediumPurple     112
#DEFINE KnownColorMediumSeaGreen     113
#DEFINE KnownColorMediumSlateBlue     114
#DEFINE KnownColorMediumSpringGreen     115
#DEFINE KnownColorMediumTurquoise     116
#DEFINE KnownColorMediumVioletRed     117
#DEFINE KnownColorMidnightBlue     118
#DEFINE KnownColorMintCream     119
#DEFINE KnownColorMistyRose     120
#DEFINE KnownColorMoccasin     121
#DEFINE KnownColorNavajoWhite     122
#DEFINE KnownColorNavy     123
#DEFINE KnownColorOldLace     124
#DEFINE KnownColorOlive     125
#DEFINE KnownColorOliveDrab     126
#DEFINE KnownColorOrange     127
#DEFINE KnownColorOrangeRed     128
#DEFINE KnownColorOrchid     129
#DEFINE KnownColorPaleGoldenrod     130
#DEFINE KnownColorPaleGreen     131
#DEFINE KnownColorPaleTurquoise     132
#DEFINE KnownColorPaleVioletRed     133
#DEFINE KnownColorPapayaWhip     134
#DEFINE KnownColorPeachPuff     135
#DEFINE KnownColorPeru     136
#DEFINE KnownColorPink     137
#DEFINE KnownColorPlum     138
#DEFINE KnownColorPowderBlue     139
#DEFINE KnownColorPurple     140
#DEFINE KnownColorRed     141
#DEFINE KnownColorRosyBrown     142
#DEFINE KnownColorRoyalBlue     143
#DEFINE KnownColorSaddleBrown     144
#DEFINE KnownColorSalmon     145
#DEFINE KnownColorSandyBrown     146
#DEFINE KnownColorSeaGreen     147
#DEFINE KnownColorSeaShell     148
#DEFINE KnownColorSienna     149
#DEFINE KnownColorSilver     150
#DEFINE KnownColorSkyBlue     151
#DEFINE KnownColorSlateBlue     152
#DEFINE KnownColorSlateGray     153
#DEFINE KnownColorSnow     154
#DEFINE KnownColorSpringGreen     155
#DEFINE KnownColorSteelBlue     156
#DEFINE KnownColorTan     157
#DEFINE KnownColorTeal     158
#DEFINE KnownColorThistle     159
#DEFINE KnownColorTomato     160
#DEFINE KnownColorTurquoise     161
#DEFINE KnownColorViolet     162
#DEFINE KnownColorWheat     163
#DEFINE KnownColorWhite     164
#DEFINE KnownColorWhiteSmoke     165
#DEFINE KnownColorYellow     166
#DEFINE KnownColorYellowGreen     167
#DEFINE KnownColorButtonFace     168
#DEFINE KnownColorButtonHighlight     169
#DEFINE KnownColorButtonShadow     170
#DEFINE KnownColorGradientActiveCaption     171
#DEFINE KnownColorGradientInactiveCaption     172
#DEFINE KnownColorMenuBar     173
#DEFINE KnownColorMenuHighlight     174